# Build customization
builds:
  - binary: crystal-bridge
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: tar.gz

dockers:
  -
    image: g0194776/crystal-bridge
    # Path to the Dockerfile (from the project root).
    tag_templates:
    - "{{ .Tag }}"
    - latest

